name: Publish Build

on:
  push:
    branches: [ "main", "steve/swiftwinrt-nuget" ]
  workflow_dispatch:

jobs:
  release-and-publish:
    runs-on: windows-2022
    name: Swift/WinRT Release Build & Publish
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/windows-build
        with:
          config: release
      - name: Get Git Hash
        id: git-hash
        shell: powershell
        run: |
          $hash=$(git log --format=%h -n1)
          Write-Output "hash: $hash"
          echo "GIT_HASH=$hash" >> $GITHUB_OUTPUT

      - name: Build Nuget
        shell: bash
        run: |
          cmake --build --preset release --target nuget -DNUGET_HASH=${{ env.GIT_HASH }}
        env:
          GIT_HASH: ${{ steps.git-hash.outputs.GIT_HASH }}

      - name: Publish NuGet Package
        shell: cmd
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_TOKEN }}
          GITHUB_USERNAME: thebrowsercompany-bot2
          NUGET_PUBLISH_URL: https://nuget.pkg.github.com/thebrowsercompany/index.json
          NUGET_SOURCE_NAME: TheBrowserCompany
        run: |
          %GITHUB_WORKSPACE%\\build\\release\\nuget push %GITHUB_WORKSPACE%\\build\\release\\*.nupkg -Source %NUGET_SOURCE_NAME%