name: Publish Build

on:
  push:
    branches: [ "main" ]
  workflow_dispath:

jobs:
  release-and-publish:
    permissions:
      packages: write
    steps:
      - uses: ./.github/workflows/windows-build.yml
        with:
          config: release
      - name: Get Git Hash
        id: git-hash
        shell: powershell
        run: |
          $hash=$(git log --format=%h -n1)
          echo "GIT_HASH=$hash" >> $GITHUB_OUTPUT

      - name: Build Nuget
        run: |
          cmake --build --preset release --target nuget -DNUGET_HASH=${{ steps.git-hash.outputs.GIT_HASH }}

      - name: Publish NuGet Package
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_TOKEN }}
          GITHUB_USERNAME: thebrowsercompany-bot2
          NUGET_PUBLISH_URL: https://nuget.pkg.github.com/thebrowsercompany/index.json
          NUGET_SOURCE_NAME: TheBrowserCompany
        run: |
          ${{github.workspace}}/build/release/nuget push ${{github.workspace}}/build/release/*.nupkg -Source ${{ env.NUGET_SOURCE_NAME }}