name: Pull Request Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Swift/WinRT PR Build & Test
    uses: ./.github/workflows/windows-build.yml
    with:
      config: debug